AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Happiness Backend

Resources:
  RequestProcessorFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: request-processor/
      Handler: app.lambda_handler
      Runtime: python3.8
      Timeout: 33
      Environment:
        Variables:
          BUCKET: !Ref BackendBucket
          TABLE: !Ref InteractionTable
      Role: "arn:aws:iam::194383749778:role/lambda_full_access"
      Events:
        HttpPost:
          Type: Api
          Properties:
            Path: '/RequestProcessor'
            Method: post


  BackendBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete

  InteractionTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
       PrimaryKey:
         Name: file
         Type: String
