<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>

	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<title>Hapiness App</title>
	<link rel="stylesheet" type="text/css" href="view.css" media="all">
	<script type="text/javascript" src="view.js"></script>
	<script src="https://sdk.amazonaws.com/js/aws-sdk-2.4.7.min.js"></script>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"></script>

	<script>

	function sendRequest ( ) {
		var text = document.getElementById("text").value;
	  var phoneNumber = document.getElementById("phoneNumber").value;
	  var mode = document.getElementById("mode").value;

		$.get("https://0mn6t0k0n0.execute-api.eu-west-1.amazonaws.com/default/Happiness-RequestProcessor", {
    	text: text,
    	phoneNumber: phoneNumber,
			mode: mode
  	},
		function(data, status){
	    alert("Data: " + data + "\nStatus: " + status);
	  });

	}

	</script>

</head>
<body id="main_body" >

	<img id="top" src="top.png" alt="">
	<div id="form_container">

		<h1><a>Happiness App</a></h1>
		<form id="form_32551" class="appnitro"  method="post" onSubmit="sendRequest()">
					<div class="form_description">
			<h2>Happiness App</h2>
			<p>Send some positive energy to others!</p>
		</div>
			<ul >

					<li id="li_1" >
		<label class="description" for="element_1">Text </label>
		<div>
			<textarea id="text" name="element_1" class="element textarea medium"></textarea>
		</div>
		</li>		<li id="li_2" >
		<label class="description" for="element_2">Phone Number </label>
		<div>
			<input id="phoneNumber" name="element_2" class="element text medium" type="text" maxlength="255" value="+48"/>
		</div>
		</li>		<li id="li_3" >
		<label class="description" for="element_3">Drop Down </label>
		<div>
		<select class="element select medium" id="mode" name="element_3">
			<option value="" selected="selected"></option>
				<option value="1" selected >Send SMS</option>
				<option value="2" >Call Me</option>

		</select>
		</div>
		</li>

					<li class="buttons">
			    <input type="hidden" name="form_id" value="32551" />

				<input id="saveForm" class="button_text" type="submit" name="submit" value="Submit" />
		</li>
			</ul>
		</form>
		<div id="footer">
			Generated by <a href="http://www.phpform.org">pForm</a>
		</div>
	</div>
	<img id="bottom" src="bottom.png" alt="">
	</body>
</html>
